image: Visual Studio 2017

environment:
  PLUGIN_API_KEY:
    secure: uRR/ys2Y9h+kLZKmAr8fm3HpQ+irhfangDguwwRkXmSpYHcKTJ07m+gwLDMvM6Ux5j6Kv1dUGBMFpOa6gtjQ+SN/ODY+ybpU1AkTVB7WCos=

build_script:
  - ps: .\build.ps1

skip_branch_with_pr: true

test: off

artifacts:
  - path: artifacts\**\*.nupkg
  - path: artifacts\**\*.zip
