image: Visual Studio 2017

environment:
  PLUGIN_API_KEY:
    secure: uRR/ys2Y9h+kLZKmAr8fm3HpQ+irhfangDguwwRkXmQy8eq1Jn0PMdTIxuZotJBZLB1ClhT2mOmm9oUn1TwUIUEGgSg+kod5RMQ0c6YvgZA=

build_script:
  - ps: .\build.ps1

skip_branch_with_pr: true

test: off

artifacts:
  - path: artifacts\**\*.nupkg
  - path: artifacts\**\*.zip
